### ISSUE TITLE
Argentina data update

### ISSUE THREAD

**Issue by iafisher** [iafisher/cityquiz-feature-and-data-requests#18]
e.g., Merlo, Quilmes

http://citypopulation.de/php/argentina-admin.php?adm1id=06

**Comment by LibTed** [comment]
I can send you a Buenos Aires dataset. The link you provided doesn't correspond to cities, but rather municipalities. I can also try to compile a full Argentina dataset as well

**Comment by iafisher** [comment]
Okay, a full Argentina data set would be fantastic. Updated issue title accordingly.

**Comment by LibTed** [comment]
Alright, I have emailed you the new dataset. I forgot to include the sources, but coordinates come from [here](http://www.bahra.gob.ar/) and population data comes from the official census and statistics institution, using two separate Excel files that they emailed me

**Comment by iafisher** [comment]
Thank you!
