### ISSUE TITLE
Remove India cities with a population of 0

### ISSUE THREAD

**Issue by iafisher** [iafisher/cityquiz-feature-and-data-requests#28]

**Comment by orasoupas** [comment]
Is there a select reason you would like to remove these? I conducted a poll on the discord server and every single person voted to keep them. A lot of these are still settlements, including a lot of now inhabited settlements since the data comes from 2011.

**Comment by iafisher** [comment]
There's more than 40,000 of them, so they are taking up a non-trivial amount of database space. And I don't see how something with a population of 0 can really be considered a settlement.

I'm willing to reconsider if you have arguments to keep them, though.

**Comment by iafisher** [comment]
@orasoupas I'm going to go ahead and do this later this week unless I hear back from you.

**Comment by orasoupas** [comment]
Sounds good to me, but speaking of database space, how much room do you think there is (by city amount), as the current database size is only a small portion of all of the new data to come.

**Comment by iafisher** [comment]
The cities themselves are actually a very small portion of the database -- more than 95% of the space is used to store user sessions. Each city costs on average 270 bytes of disk space.

**Comment by iafisher** [comment]
This has been now done.
